### ISSUE TITLE
Create unit tests for hashing

### ISSUE THREAD

**Issue by protojas** [jeff1evesque/machine-learning#2706]
Create a unit test to make sure that hashing two values results in different hashes, and that verifying the same password against two legitimate hashes works correctly. These are for the functions implemented in #2700.

**Comment by jeff1evesque** [comment]
This issue is a great idea, and great way to verify #2700, since it hasn't been incorporated into the application.  I was going to write more granular unit tests on [milestone 1.0](https://github.com/jeff1evesque/machine-learning/milestone/4).  But, best practices should be to write unit tests as you develop, as you've done.
