### ISSUE TITLE
Ensure current svm can be bootstrapped (classifier)

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/machine-learning#3040]
We need to ensure that the current svm implementation, can serve as an estimator, for the bootstrap aggregation.  More generally, this issue is a successor of #3025.

**Comment by protojas** [comment]
you can't feed an existing estimator into the bagging classifier as far as I can tell

what you *can* do is give it parameters for how to make SVCs and it'll create it's own internal models  while computing the bagging.

(remember that it creates multiple SVC models for different datasets generated from the original training dataset. so it wouldn't make sense to feed it a model that's already been trained, because it bagging is just a special way of mixing up data before training happens.)

**Comment by jeff1evesque** [comment]
Closing issue per [above](https://github.com/jeff1evesque/machine-learning/issues/3040#issuecomment-334981370) statement.
