### ISSUE TITLE
Create AdaBoost Wrapper (Classifier)

### ISSUE THREAD

**Issue by protojas** [jeff1evesque/machine-learning#3049]
Create a python function for the ada boost classifier methods which supports SVC, KNN, RF, and normal decision trees.

**Comment by jeff1evesque** [comment]
@protojas keep your commit messages under 55 characters, it's going to break the checks during PR's.

**Comment by jeff1evesque** [comment]
Can you adjust the committed files in this issue to be similar notation to [`bagger.py`](https://github.com/jeff1evesque/machine-learning/blob/9f2ccba0f7adb69718a0fcf4e9b65175cacdbf44/brain/session/model/bagger.py).  Also, try to keep the commit message under 55 characters, otherwise, it will break the gitmagic checker during PR.  I can fix your current commit messages when it comes to the PR. But, it gets tedious if i have to fix every commit message.

**Comment by protojas** [comment]
ok will do

**Comment by protojas** [comment]
whoops I think I went over 55 characters

**Comment by jeff1evesque** [comment]
You can submit a PR on this request if it's ready. Otherwise, I'd have to `git pull` from your fork to submit a PR. Remember to have the PR merge into `milestone-0.9`:

![merge](https://user-images.githubusercontent.com/2907085/31852764-c2c06cfc-b64b-11e7-80fd-d8bdacd343aa.JPG)

**Comment by protojas** [comment]
how do I do a pull request to milestone-0.9 again?

**Comment by jeff1evesque** [comment]
You do it through the web browser, a link on the top labelled 'Pull Request'. Don't `git merge` manually.

**Comment by jeff1evesque** [comment]
I've closed the corresponding pull request via https://github.com/jeff1evesque/machine-learning/pull/3077.
